### ISSUE TITLE
Selecting a red (unknown) title still works (at least with LSM v2.2 (I guess v2.1 too)

### ISSUE THREAD

**Issue by Baertram** [tomstock1337/eso-ImprovedTitleizer#5]
Clicking a non-disabled entry (red one) for unknown title still selects it! It does not call SelectTitle but still the combox shows that entry as selected. This should not happen.
So one would need to find another way to show the tooltip but not enable and selection.

**Comment by tomstock1337** [comment]
I submitted an issue to LSM to allow tooltips to be viewable on disabled menu items.

**Comment by Baertram** [comment]
I closed that one, you cannot do that by Zos design.
But you can do this -> with LSM v2.2

callback= (hasTitle and function() SelectTitle(vTitle.TitleID) end) or nil,

if callback is nil it still shows the tooltip but is not selectable
I guess that won't work with v2.1 though so you'd need to test it

**Comment by Baertram** [comment]
Works as designed.
Enabled entries will always be selectible unless you remove the callback function (set it to nil).
